# Generated by Django 5.2 on 2025-06-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(default='img/default_profile.png', upload_to='perfil_fotos/'),
        ),
    ]
