# Generated by Django 5.2 on 2025-06-01 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_artigo_autor_alter_perfil_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='criado_em',
        ),
    ]
