# Generated by Django 5.2 on 2025-06-01 21:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_comentario_criado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='criado_em',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
