# Generated by Django 5.2 on 2025-06-02 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_artigo_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artigo',
            name='imagem',
        ),
    ]
